from gtts import gTTS
import subprocess
import os

SCRIPTS = [
    (("Deep Sleep Meditation", """
Welcome to Sleep and Calm. 
Tonight, you are giving yourself the greatest gift you can give... the gift of rest.
Find a comfortable position. Let your body sink into the surface beneath you.
Close your eyes gently. There is nowhere to be. Nothing to do. No one to answer to.
Just this moment. Just this breath.

Take a slow deep breath in through your nose... hold it gently... and release slowly through your mouth.
Again... breathe in... and out... feel your body becoming heavier with each breath.
Your feet are relaxing... your ankles... your calves... all tension leaving now.
Your knees soften... your thighs release... your hips drop and open.
Your lower back flattens and relaxes... your stomach rises and falls with each peaceful breath.
Your chest opens... your shoulders drop away from your ears...
your arms are heavy... your hands are open and soft.
Your neck releases all tension... your jaw unclenches... your tongue rests at the bottom of your mouth.
Your eyes are still behind their lids... your forehead is smooth and calm.
Your entire body is now completely relaxed.

Now imagine yourself lying in a field of soft green grass on a warm summer night.
The sky above you is a deep dark blue, scattered with thousands of tiny stars.
A gentle warm breeze moves across your skin, carrying the scent of flowers and fresh earth.
You can hear crickets singing softly in the distance.
You feel completely safe here. Completely at peace. Completely free.

With each breath you take, you sink deeper into this peaceful place.
Deeper into relaxation. Deeper into calm. Deeper into sleep.
Your thoughts begin to slow down... like clouds drifting lazily across the night sky...
each thought appears for a moment... and then floats away... gently... effortlessly.
You do not need to hold onto any thought tonight. Just let them pass.

The stars above you seem to pulse gently with a soft white light.
This light begins to fall down upon you like the softest rain you have ever felt.
It touches your forehead first... filling you with peace...
it moves down through your face... your neck... your shoulders...
carrying away any remaining tension... any worry... any stress.
The light fills your chest with warmth... your stomach with calm...
your legs with heaviness... your feet with stillness.
You are now completely filled with this peaceful healing light.

Your breathing has slowed to a deep and natural rhythm.
In... and out... in... and out...
each breath taking you deeper and deeper into the most restful sleep you have ever known.
Your body is healing with every breath. Your mind is clearing with every exhale.
Tomorrow you will wake feeling refreshed, renewed, and ready for whatever comes.
But for now... there is only this moment... this breath... this beautiful peaceful darkness.

You are safe. You are loved. You are exactly where you need to be.
Let go of everything now. The night will take care of you.
Drift deeper... and deeper... and deeper still...
into perfect, healing, beautiful sleep.

Goodnight. Sleep well. You deserve this rest.
"""),),
    ("Rain Sound Relaxation", """
Welcome to Sleep and Calm. Make yourself comfortable and gently close your eyes.
Listen to the gentle rain falling softly outside...
each drop washes away your stress... your worry... your tension...
Your mind becomes still and quiet... like a calm lake after the rain...
breathe slowly... in... and out... you are completely relaxed...
The rain holds you... soothes you... carries you into deep restful sleep.
Goodnight, and sleep well.
"""),
    ("Body Scan Sleep", """
Welcome to Sleep and Calm. Lie down and let your body sink into comfort.
Begin at your toes... feel them relax completely...
move up to your feet... your ankles...
your legs are heavy and warm...
your stomach softens with every breath...
your chest rises and falls gently...
your arms are heavy... your hands are open and relaxed...
your face is soft... your eyes are still...
your entire body is at peace... sleep comes to you now.
Goodnight, and sleep well.
"""),
    ("Midnight Calm", """
Welcome to Sleep and Calm. Close your eyes and let the night hold you.
The night is quiet and peaceful... stars are shining above you...
you are wrapped in warmth and safety...
every breath takes you deeper into relaxation...
let go of all thoughts... they can wait until tomorrow...
tonight belongs to you... to your rest... to your healing.
Goodnight, and sleep well.
"""),
    ("Forest Sleep Journey", """
Welcome to Sleep and Calm. Settle in and let your imagination carry you.
Imagine you are lying in a peaceful forest...
birds are singing softly in the distance...
a gentle breeze touches your face...
the smell of earth and leaves fills the air...
nature surrounds you with calm healing energy...
you are safe here... completely at peace...
breathe in the fresh forest air... and sleep now.
Goodnight, and sleep well.
"""),
    ("Ocean Wave Sleep", """
Welcome to Sleep and Calm. Rest your body and listen to the ocean.
Waves are gently rolling to shore... in and out... in and out...
your breathing matches the rhythm of the ocean...
slow and steady... slow and steady...
your mind is clear and empty... like the horizon at night...
the ocean holds you... rocks you gently... into deep sleep.
Goodnight, and sleep well.
"""),
    ("Anxiety Release Meditation", """
Welcome to Sleep and Calm. You are safe here. Let everything go.
Release all worries now... they do not serve you tonight...
breathe out tension... breathe in peace...
your chest feels lighter with every breath...
your mind feels free... clear... open...
tonight you sleep without fear... without worry... without stress.
You are safe. You are calm. You are loved.
Goodnight, and sleep well.
"""),
    ("Gratitude Sleep", """
Welcome to Sleep and Calm. Let warmth fill your heart tonight.
Think of one good thing from today... just one...
hold it gently in your mind... feel warmth spreading through your chest...
you are grateful... you are blessed... you are enough...
carry this peaceful feeling with you into deep restful sleep.
Tomorrow will take care of itself. Tonight, just rest.
Goodnight, and sleep well.
"""),
    ("Healing Sleep", """
Welcome to Sleep and Calm. Your body knows how to heal. Trust it tonight.
As you sleep tonight your body heals...
your mind resets... your energy restores...
every cell in your body is working to make you stronger...
you wake up tomorrow feeling refreshed... renewed... and ready...
sleep is your superpower... use it fully tonight.
Goodnight, and sleep well.
"""),
    ("White Light Relaxation", """
Welcome to Sleep and Calm. Close your eyes and imagine a gentle light.
Imagine a warm white light glowing softly above you...
it slowly moves down through the top of your head...
through your neck... your shoulders...
melting away all tension as it goes...
filling every part of you with warmth and peace...
you are completely relaxed... completely safe... completely at rest.
Goodnight, and sleep well.
"""),
    ("Stress Release", """
Welcome to Sleep and Calm. Today is done. You can let it go now.
Whatever happened today is over... you did your best...
that is always enough... now it is time to rest...
let your shoulders drop... unclench your jaw...
soften your hands... relax your face...
breathe in peace... breathe out everything else.
Goodnight, and sleep well.
"""),
    ("Mindful Breathing Sleep", """
Welcome to Sleep and Calm. Let your breath guide you to sleep.
Focus only on your breath... nothing else matters right now...
breathe in for four counts... one... two... three... four...
hold for four... one... two... three... four...
breathe out for four... one... two... three... four...
again... in... hold... out...
your mind is calm... your body is ready for sleep.
Goodnight, and sleep well.
"""),
    ("Peaceful Night", """
Welcome to Sleep and Calm. The world is quiet. You can be too.
Everyone is resting now... the city is still... the sky is dark...
you deserve rest just as much as anyone...
close your eyes and let the darkness comfort you...
this is your safe time... your healing time... your peaceful time.
Goodnight, and sleep well.
"""),
    ("Cloud Visualization", """
Welcome to Sleep and Calm. Let your mind float free tonight.
Imagine floating on a soft white cloud...
it holds you gently... perfectly...
you drift higher into the calm night sky...
everything below feels small and far away...
you feel weightless... free... completely at peace.
Goodnight, and sleep well.
"""),
    ("Mountain Peace", """
Welcome to Sleep and Calm. Find stillness in the mountains tonight.
Picture a calm mountain lake at night...
the water is perfectly still... like glass...
reflecting the moonlight in silver ripples...
you sit peacefully by the shore...
breathing cool fresh mountain air...
your heart is quiet... your mind is clear... sleep comes easily.
Goodnight, and sleep well.
"""),
    ("Moonlight Sleep", """
Welcome to Sleep and Calm. Let the moon watch over you tonight.
The moon is shining softly through your window...
it watches over you as you sleep...
you are protected... you are loved... you are held...
the silver moonlight brings you calmness...
and deep healing sleep.
Goodnight, and sleep well.
"""),
    ("Inner Peace Journey", """
Welcome to Sleep and Calm. Go inside yourself and find the quiet.
Go deep inside yourself now...
find that quiet place within...
it is always there waiting for you...
in this place there is no worry... no rush... no noise...
only stillness... and peace... and rest.
Stay here tonight. Sleep here tonight.
Goodnight, and sleep well.
"""),
    ("Tension Release", """
Welcome to Sleep and Calm. Let your body release everything it is holding.
Start with your forehead... relax it completely...
now your eyes... let them be still and heavy...
your cheeks... your jaw... let it drop slightly...
feel the tension leaving your face...
moving down through your neck... your shoulders...
your arms... your hands...
you are melting into rest.
Goodnight, and sleep well.
"""),
    ("Positive Dreams", """
Welcome to Sleep and Calm. Beautiful dreams are waiting for you.
Tonight you will have peaceful beautiful dreams...
your mind is ready to take you on a gentle journey...
full of color... warmth... and joy...
close your eyes and welcome whatever comes...
trust that tonight will be restful and healing.
Goodnight, and sleep well.
"""),
    ("Energy Reset", """
Welcome to Sleep and Calm. Recharge your body and mind tonight.
Your body has worked hard today... now it needs to recharge...
like a phone plugged in at night...
you are restoring your energy...
every minute of sleep makes you stronger...
every breath brings you closer to full restoration.
Sleep fully and deeply tonight.
Goodnight, and sleep well.
"""),
    ("Letting Go Sleep", """
Welcome to Sleep and Calm. Practice the art of letting go.
Let go of yesterday... it is done...
let go of tomorrow... it has not come yet...
there is only this moment... this breath...
this peaceful darkness around you...
nothing needs your attention right now...
everything can wait... just sleep and restore.
Goodnight, and sleep well.
"""),
    ("Deep Rest", """
Welcome to Sleep and Calm. Your body knows how to rest. Let it.
You are entering deep rest now...
your heart rate slows... your breathing deepens...
your brain shifts into sleep mode...
your body knows exactly what to do...
trust the process... surrender to the night.
Goodnight, and sleep well.
"""),
    ("Comfort Sleep", """
Welcome to Sleep and Calm. Feel how comfortable you already are.
You are in the most comfortable position right now...
your pillow supports you perfectly...
your blanket is warm... everything is just right...
you have nothing to do but sleep...
nowhere to be... nothing to think about...
just enjoy this perfect moment of comfort.
Goodnight, and sleep well.
"""),
    ("Night Sky Meditation", """
Welcome to Sleep and Calm. Look up at the infinite night sky.
Look up at the endless night sky in your mind...
count the stars slowly with me...
one... two... three... four... five...
each star takes you deeper into relaxation...
six... seven... eight...
your eyes are heavy... nine...
you are almost asleep... ten.
Goodnight, and sleep well.
"""),
    ("Gentle Wind Sleep", """
Welcome to Sleep and Calm. Feel the gentle wind carry your worries away.
A gentle warm wind blows softly around you...
it carries away all stress... all worry...
all heaviness from your day...
you feel lighter with every breath...
the wind wraps around you like a warm blanket...
and sings you softly to sleep.
Goodnight, and sleep well.
"""),
    ("Garden of Rest", """
Welcome to Sleep and Calm. Walk with me through a peaceful night garden.
Walk slowly through a beautiful night garden...
jasmine flowers fill the air with sweetness...
soft cool grass under your bare feet...
fireflies dancing gently all around you...
find your favourite bench and sit...
breathe in the garden... close your eyes... and sleep.
Goodnight, and sleep well.
"""),
    ("Sound of Silence", """
Welcome to Sleep and Calm. Listen to the beautiful silence around you.
Listen to the silence around you...
in the silence there is peace...
in the silence there is safety...
breathe into the silence...
let it fill your lungs... your heart... your mind...
you are one with the calm quiet night.
Goodnight, and sleep well.
"""),
    ("Waterfall Calm", """
Welcome to Sleep and Calm. Let the sound of water carry you to sleep.
Hear a distant waterfall in your mind...
the constant gentle sound soothes every thought...
it fills your mind so completely...
that nothing else can enter...
just the water... flowing endlessly... peacefully...
carrying you deeper and deeper into sleep.
Goodnight, and sleep well.
"""),
    ("Starlight Sleep", """
Welcome to Sleep and Calm. Let starlight heal you as you sleep.
Starlight falls gently on you tonight...
each tiny ray carries healing energy...
filling you with calm... with peace... with love...
your body absorbs this light...
every cell relaxes... every muscle softens...
you glow with peaceful energy.
Goodnight, and sleep well.
"""),
    ("Final Rest", """
Welcome to Sleep and Calm. This moment belongs entirely to you.
This is your time now...
no phone... no worries... no tomorrow...
just you... and this moment... and this peace...
you have earned this rest...
take it fully... completely... gratefully...
breathe slowly... close your eyes...
and sleep.
Goodnight, and sleep well.
"""),
]

def generate_audio(text, filename):
    tts = gTTS(text=text, lang='en', slow=True)
    tts.save(filename)

def mix_audio(voice_file, music_file, output_file):
    subprocess.run([
        "ffmpeg",
        "-i", voice_file,
        "-i", music_file,
        "-filter_complex", "[1:a]volume=0.12[bg];[0:a][bg]amix=inputs=2:duration=first",
        "-y", output_file
    ])

def create_video(audio_file, animation_file, output_file):
    subprocess.run([
        "ffmpeg",
        "-stream_loop", "-1",
        "-i", animation_file,
        "-i", audio_file,
        "-shortest",
        "-c:v", "libx264",
        "-c:a", "aac",
        "-b:a", "192k",
        "-y",
        output_file
    ])

day = int(os.environ.get("DAY_OFFSET", 0)) % len(SCRIPTS)
title, script = SCRIPTS[day]

print(f"Generating: {title}")
generate_audio(script, "voice.mp3")

if os.path.exists("animations/music.mp3"):
    print("Mixing music...")
    mix_audio("voice.mp3", "animations/music.mp3", "audio.mp3")
else:
    print("No music found, using voice only...")
    os.rename("voice.mp3", "audio.mp3")

create_video("audio.mp3", "animations/rain_loop.mp4", "output.mp4")
print(f"Done! Video ready: {title}")
